{
 "title": "Data Platform Logs",
 "tags": [
  "platform",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "PostgreSQL Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-postgres\"}"
    }
   ]
  },
  {
   "title": "MinIO Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-minio\"}"
    }
   ]
  },
  {
   "title": "MLflow Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-mlflow\"}"
    }
   ]
  },
  {
   "title": "Pipeline Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-pipeline\"}"
    }
   ]
  },
  {
   "title": "DBT Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-dbt\"}"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{container_name=\"analytics-loki\"}"
    }
   ]
  }
 ]
}