version: 2

models:
  - name: stg_commits
    description: Staged and cleaned commit data
    columns:
      - name: commit_sha
        description: Unique commit identifier
        tests:
          - unique
          - not_null
      - name: author_email
        description: Normalized author email (lowercase, trimmed)
        tests:
          - not_null
      - name: author_date
        description: Commit authoring timestamp
        tests:
          - not_null
      - name: commit_message
        description: Cleaned commit message
        tests:
          - not_null
      - name: message_length
        description: Length of commit message in characters
        tests:
          - not_null
      - name: is_merge_commit
        description: Flag indicating if this is a merge commit
